import type { Question } from "@/types/quiz";

/**
 * Robustly extract numeric chapter number from string IDs or numbers
 * Examples: "ch1" -> 1, "ch15" -> 15, "Chapter 5" -> 5, 8 -> 8
 */
export function parseChapterNumber(chapter: string | number): number {
  if (typeof chapter === "number" && !isNaN(chapter)) return chapter;
  const str = String(chapter);
  const match = str.match(/\d+/);
  return match ? parseInt(match[0], 10) : 1;
}

export const ALL_CHAPTER_QUESTIONS: Record<number, Question[]> = {
  // Chapter 1: Digestive System of Man
  1: [
    {
      id: "ch1-q1",
      sessionId: "demo",
      questionText: "Which component of gastric juice provides the acidic medium necessary for pepsinogen activation?",
      optionA: "Hydrochloric acid (HCl)",
      optionB: "Sodium bicarbonate",
      optionC: "Mucus",
      optionD: "Intrinsic factor",
      correctAnswer: "A",
      explanationEn: "Parietal cells in the stomach secrete Hydrochloric Acid (HCl), which lowers gastric pH to 1.5–2.0. This low pH converts inactive pepsinogen into active pepsin.",
      explanationUr: "Stomach ke parietal cells Hydrochloric Acid (HCl) secrete karte hain jo pH ko 1.5-2.0 tak kam karta hai aur pepsinogen ko active pepsin mein convert karta hai.",
      difficulty: "Easy",
      topic: "Digestive System of Man",
    },
    {
      id: "ch1-q2",
      sessionId: "demo",
      questionText: "Where does the major site of nutrient absorption occur in the human digestive system?",
      optionA: "Stomach",
      optionB: "Duodenum",
      optionC: "Jejunum and Ileum",
      optionD: "Large Intestine",
      correctAnswer: "C",
      explanationEn: "The jejunum and ileum contain millions of microscopic villi and microvilli, maximizing the surface area for nutrient absorption into blood and lymph.",
      explanationUr: "Jejunum aur ileum mein millions of microvilli hote hain jo surface area barhate hain taake maximum nutrients absorb ho sakein.",
      difficulty: "Medium",
      topic: "Digestive System of Man",
    },
    {
      id: "ch1-q3",
      sessionId: "demo",
      questionText: "Emulsification of fats in the small intestine is carried out by which liver secretion?",
      optionA: "Pancreatic lipase",
      optionB: "Bile salts",
      optionC: "Gastric lipase",
      optionD: "Trypsinogen",
      correctAnswer: "B",
      explanationEn: "Bile salts synthesized by the liver and stored in the gallbladder break down large lipid globules into smaller droplets (emulsification) to increase lipase surface area.",
      explanationUr: "Bile salts bare lipid drops ko chote droplets mein break (emulsify) karte hain taake lipase enzyme unhein digest kar sake.",
      difficulty: "Easy",
      topic: "Digestive System of Man",
    },
    {
      id: "ch1-q4",
      sessionId: "demo",
      questionText: "Which digestive enzyme initiates carbohydrate digestion in the human mouth?",
      optionA: "Salivary Amylase (Ptyalin)",
      optionB: "Pepsin",
      optionC: "Maltase",
      optionD: "Pancreatic Lipase",
      correctAnswer: "A",
      explanationEn: "Salivary amylase (ptyalin) secreted by salivary glands hydrolyzes cooked starch into maltose and dextrins at neutral pH in the oral cavity.",
      explanationUr: "Salivary amylase (ptyalin) mouth mein starch ko maltose mein break karke carbohydrate digestion shuru karta hai.",
      difficulty: "Easy",
      topic: "Digestive System of Man",
    },
    {
      id: "ch1-q5",
      sessionId: "demo",
      questionText: "Which intestinal hormone stimulates the gallbladder to contract and release stored bile into the duodenum?",
      optionA: "Gastrin",
      optionB: "Secretin",
      optionC: "Cholecystokinin (CCK)",
      optionD: "Enterogastrone",
      correctAnswer: "C",
      explanationEn: "Cholecystokinin (CCK) released by duodenal mucosa in response to fatty chyme stimulates gallbladder contraction and pancreatic enzyme secretion.",
      explanationUr: "Cholecystokinin (CCK) hormone gallbladder ko contract karta hai taake bile duodenum mein release ho sake.",
      difficulty: "Hard",
      topic: "Digestive System of Man",
    },
    {
      id: "ch1-q6",
      sessionId: "demo",
      questionText: "What is the primary physiological function of the large intestine (colon)?",
      optionA: "Protein digestion by trypsin",
      optionB: "Reabsorption of water and electrolytes",
      optionC: "Secretion of bile salts",
      optionD: "Fat absorption into lacteals",
      correctAnswer: "B",
      explanationEn: "The large intestine absorbs remaining water, sodium, and chloride ions from indigestible chyme, concentrating waste into solid feces.",
      explanationUr: "Large intestine bache hue paani aur electrolytes ko reabsorb karke waste ko solid feces mein convert karti hai.",
      difficulty: "Easy",
      topic: "Digestive System of Man",
    },
  ],

  // Chapter 2: Blood Circulatory System of Man
  2: [
    {
      id: "ch2-q1",
      sessionId: "demo",
      questionText: "Which cardiac tissue structure acts as the primary natural pacemaker of the human heart?",
      optionA: "Atrioventricular (AV) node",
      optionB: "Sinoatrial (SA) node",
      optionC: "Bundle of His",
      optionD: "Purkinje fibers",
      correctAnswer: "B",
      explanationEn: "The Sinoatrial (SA) node located in the upper wall of the right atrium generates spontaneous action potentials that set the cardiac rhythm.",
      explanationUr: "Sinoatrial (SA) node right atrium mein hota hai aur spontaneous electrical signals generate karta hai jo heart rate set karte hain.",
      difficulty: "Easy",
      topic: "Blood Circulatory System of Man",
    },
    {
      id: "ch2-q2",
      sessionId: "demo",
      questionText: "Which blood vessels possess the thickest muscular tunica media to withstand high systolic pressure?",
      optionA: "Capillaries",
      optionB: "Veins",
      optionC: "Arteries",
      optionD: "Venules",
      correctAnswer: "C",
      explanationEn: "Arteries carry high-pressure oxygenated blood away from the ventricles and contain prominent smooth muscle and elastic fibers in their tunica media.",
      explanationUr: "Arteries high pressure blood carry karti hain is liye unki middle muscular layer (tunica media) sab se ziada thick hoti hai.",
      difficulty: "Medium",
      topic: "Blood Circulatory System of Man",
    },
    {
      id: "ch2-q3",
      sessionId: "demo",
      questionText: "What causes the first heart sound (S1 - 'Lub') during the cardiac cycle?",
      optionA: "Closure of aortic and pulmonary semilunar valves",
      optionB: "Closure of tricuspid and bicuspid (mitral) AV valves",
      optionC: "Opening of semilunar valves",
      optionD: "Rapid ventricular filling",
      correctAnswer: "B",
      explanationEn: "The first heart sound (Lub) is produced by the simultaneous closure of the atrioventricular (tricuspid and mitral) valves at the onset of ventricular systole.",
      explanationUr: "Pehli heart sound (Lub) ventricular systole ke shuru mein AV valves (tricuspid aur mitral) ke band hone se paida hoti hai.",
      difficulty: "Medium",
      topic: "Blood Circulatory System of Man",
    },
    {
      id: "ch2-q4",
      sessionId: "demo",
      questionText: "Which blood plasma protein is primarily responsible for maintaining blood colloid osmotic pressure?",
      optionA: "Fibrinogen",
      optionB: "Albumin",
      optionC: "Gamma globulin",
      optionD: "Prothrombin",
      correctAnswer: "B",
      explanationEn: "Albumin accounts for ~60% of plasma proteins and generates the oncotic pressure preventing excess fluid leakage from capillaries into interstitial space.",
      explanationUr: "Albumin plasma ka sab se aham protein hai jo capillary oncotic pressure maintain karke tissue swelling rokta hai.",
      difficulty: "Easy",
      topic: "Blood Circulatory System of Man",
    },
    {
      id: "ch2-q5",
      sessionId: "demo",
      questionText: "In the human blood clotting cascade, inactive prothrombin is converted into active thrombin by:",
      optionA: "Fibrinogen",
      optionB: "Prothrombinase (Thromboplastin complex)",
      optionC: "Plasmin",
      optionD: "Heparin",
      correctAnswer: "B",
      explanationEn: "Prothrombinase complex (Factor Xa + Factor Va + Calcium) converts prothrombin into active thrombin, which then cleaves soluble fibrinogen into insoluble fibrin.",
      explanationUr: "Prothrombinase complex prothrombin ko active thrombin mein badalta hai jo fibrin mesh banata hai.",
      difficulty: "Hard",
      topic: "Blood Circulatory System of Man",
    },
  ],

  // Chapter 3: Respiratory System of Man
  3: [
    {
      id: "ch3-q1",
      sessionId: "demo",
      questionText: "What is the primary physical mechanism by which oxygen moves across the alveolar-capillary membrane?",
      optionA: "Active transport",
      optionB: "Simple diffusion",
      optionC: "Facilitated diffusion",
      optionD: "Osmosis",
      correctAnswer: "B",
      explanationEn: "Gas exchange across the ultra-thin respiratory membrane occurs via passive simple diffusion down partial pressure gradients.",
      explanationUr: "Alveoli aur capillaries ke darmiyan oxygen aur CO2 ka exchange passive simple diffusion ke zariye hota hai.",
      difficulty: "Easy",
      topic: "Respiratory System of Man",
    },
    {
      id: "ch3-q2",
      sessionId: "demo",
      questionText: "The central chemoreceptors in the brainstem medulla oblongata are most sensitive to changes in:",
      optionA: "Arterial PO2",
      optionB: "Cerebrospinal fluid H+ / CO2 concentration",
      optionC: "Blood glucose levels",
      optionD: "Blood pressure",
      correctAnswer: "B",
      explanationEn: "Central chemoreceptors monitor H+ ions generated from CO2 diffusion across the blood-brain barrier into cerebrospinal fluid.",
      explanationUr: "Medulla ke central chemoreceptors CO2 aur H+ ions (pH) ke levels se primarily respiratory rate control karte hain.",
      difficulty: "Medium",
      topic: "Respiratory System of Man",
    },
    {
      id: "ch3-q3",
      sessionId: "demo",
      questionText: "The majority (~70%) of carbon dioxide generated by tissue metabolism is transported in blood as:",
      optionA: "Dissolved CO2 gas in plasma",
      optionB: "Carbaminohemoglobin",
      optionC: "Bicarbonate ions (HCO3-) in plasma",
      optionD: "Carbonic acid molecules",
      correctAnswer: "C",
      explanationEn: "RBC carbonic anhydrase converts CO2 + H2O -> H2CO3 -> H+ + HCO3-. Bicarbonate ions diffuse out into plasma via chloride shift.",
      explanationUr: "Taqreeban 70% CO2 blood plasma mein Bicarbonate ions (HCO3-) ki shakal mein transport hoti hai.",
      difficulty: "Medium",
      topic: "Respiratory System of Man",
    },
    {
      id: "ch3-q4",
      sessionId: "demo",
      questionText: "What pulmonary substance secreted by Type II alveolar cells reduces surface tension to prevent lung collapse?",
      optionA: "Mucus",
      optionB: "Surfactant (Dipalmitoylphosphatidylcholine)",
      optionC: "Histamine",
      optionD: "Heparin",
      correctAnswer: "B",
      explanationEn: "Pulmonary surfactant decreases alveolar surface tension, preventing small alveoli from collapsing (atelectasis) during expiration.",
      explanationUr: "Type II alveolar cells se nikalne wala Surfactant alveolar surface tension kam karke lungs ko collapse hone se bachat karta hai.",
      difficulty: "Medium",
      topic: "Respiratory System of Man",
    },
  ],

  // Chapter 4: Urinary System of Man
  4: [
    {
      id: "ch4-q1",
      sessionId: "demo",
      questionText: "Ultrafiltration of blood plasma in the nephron occurs across the glomerular capillaries into:",
      optionA: "Proximal Convoluted Tubule",
      optionB: "Bowman's Capsule",
      optionC: "Loop of Henle",
      optionD: "Collecting Duct",
      correctAnswer: "B",
      explanationEn: "High blood pressure in glomerulus forces water and small solutes through fenestrated capillaries and podocytes into Bowman's space.",
      explanationUr: "Glomerulus ki high blood pressure plasma ko filter karke Bowman's capsule ke andar bhejti hai.",
      difficulty: "Easy",
      topic: "Urinary System of Man",
    },
    {
      id: "ch4-q2",
      sessionId: "demo",
      questionText: "Which region of the nephron reabsorbs the largest percentage (~65-70%) of filtered water, glucose, and essential ions?",
      optionA: "Proximal Convoluted Tubule (PCT)",
      optionB: "Descending Loop of Henle",
      optionC: "Distal Convoluted Tubule (DCT)",
      optionD: "Collecting Duct",
      correctAnswer: "A",
      explanationEn: "The PCT lined with brush border microvilli reabsorbs 100% of filtered glucose/amino acids and ~65-70% of Na+ and water.",
      explanationUr: "Proximal Convoluted Tubule (PCT) 100% glucose aur 65-70% paani aur ions ko wapas blood mein reabsorb karta hai.",
      difficulty: "Medium",
      topic: "Urinary System of Man",
    },
    {
      id: "ch4-q3",
      sessionId: "demo",
      questionText: "Anti-Diuretic Hormone (ADH / Vasopressin) concentrates urine primarily by increasing water permeability in:",
      optionA: "Glomerulus",
      optionB: "Bowman's capsule",
      optionC: "Distal Tubules and Collecting Ducts",
      optionD: "Ascending Loop of Henle",
      correctAnswer: "C",
      explanationEn: "ADH triggers aquaporin-2 channel insertion into collecting duct principal cells, reabsorbing water back into renal medullary capillaries.",
      explanationUr: "ADH collecting ducts mein aquaporin paani ke raste insert karta hai jis se urine concentrate hota hai.",
      difficulty: "Medium",
      topic: "Urinary System of Man",
    },
  ],

  // Chapter 5: Nervous System of Man
  5: [
    {
      id: "ch5-q1",
      sessionId: "demo",
      questionText: "Which of the following is the basic structural and functional unit of the nervous system?",
      optionA: "Nephron",
      optionB: "Neuron",
      optionC: "Hepatocyte",
      optionD: "Chondrocyte",
      correctAnswer: "B",
      explanationEn: "The neuron is specialized for receiving, processing, and transmitting electro-chemical nerve impulses.",
      explanationUr: "Neuron nervous system ki basic structural aur functional unit hai jo electrical signals transmit karta hai.",
      difficulty: "Easy",
      topic: "Nervous System of Man",
    },
    {
      id: "ch5-q2",
      sessionId: "demo",
      questionText: "The resting membrane potential (-70mV) of a neuron is actively maintained by:",
      optionA: "Sodium-Potassium ATPase Pump",
      optionB: "Calcium channels",
      optionC: "Chloride pumps",
      optionD: "Proton pumps",
      correctAnswer: "A",
      explanationEn: "The Na+/K+ pump actively transports 3 Na+ out of the neuron for every 2 K+ inside, creating resting polarization.",
      explanationUr: "Na+/K+ pump 3 Na+ bahar aur 2 K+ andar pump karke resting membrane potential (-70mV) maintain karta hai.",
      difficulty: "Medium",
      topic: "Nervous System of Man",
    },
    {
      id: "ch5-q3",
      sessionId: "demo",
      questionText: "During neuron depolarization, which ion channels open first in response to threshold stimulus?",
      optionA: "Potassium channels",
      optionB: "Voltage-gated Sodium (Na+) channels",
      optionC: "Chloride channels",
      optionD: "Calcium channels",
      correctAnswer: "B",
      explanationEn: "Threshold stimulus opens voltage-gated Na+ channels, causing rapid Na+ influx that reverses membrane potential from -70mV to +30mV.",
      explanationUr: "Depolarization mein voltage-gated Na+ channels khulte hain jis se Na+ andar aate hain aur membrane potential positive ho jata hai.",
      difficulty: "Medium",
      topic: "Nervous System of Man",
    },
    {
      id: "ch5-q4",
      sessionId: "demo",
      questionText: "Rapid impulse jumping between Nodes of Ranvier in myelinated axons is known as:",
      optionA: "Continuous conduction",
      optionB: "Saltatory conduction",
      optionC: "Synaptic transmission",
      optionD: "Refractory period",
      correctAnswer: "B",
      explanationEn: "Saltatory conduction occurs in myelinated neurons where action potential jumps from one Node of Ranvier to the next.",
      explanationUr: "Myelinated neurons mein nerve impulse Nodes of Ranvier ke darmiyan jump karke jata hai jise Saltatory conduction kehte hain.",
      difficulty: "Easy",
      topic: "Nervous System of Man",
    },
    {
      id: "ch5-q5",
      sessionId: "demo",
      questionText: "Deficiency of which neurotransmitter in the basal forebrain is primarily linked with Alzheimer's disease?",
      optionA: "Dopamine",
      optionB: "Acetylcholine",
      optionC: "Serotonin",
      optionD: "GABA",
      correctAnswer: "B",
      explanationEn: "Degeneration of cholinergic neurons leading to Acetylcholine deficiency causes memory loss in Alzheimer's disease.",
      explanationUr: "Acetylcholine ki kami Alzheimer's disease se associated hai jis se yaadashat mutassir hoti hai.",
      difficulty: "Hard",
      topic: "Nervous System of Man",
    },
  ],

  // Chapter 6: Endocrine System of Man
  6: [
    {
      id: "ch6-q1",
      sessionId: "demo",
      questionText: "Which pancreatic hormone lowers blood glucose levels by promoting cellular glucose uptake and glycogenesis?",
      optionA: "Glucagon",
      optionB: "Insulin",
      optionC: "Cortisol",
      optionD: "Somatostatin",
      correctAnswer: "B",
      explanationEn: "Insulin secreted by beta cells of pancreatic islets of Langerhans promotes glucose uptake into muscle and adipose tissues.",
      explanationUr: "Pancreatic beta cells se nikalne wala Insulin blood glucose ko cells mein bhej kar sugar kam karta hai.",
      difficulty: "Easy",
      topic: "Endocrine System of Man",
    },
    {
      id: "ch6-q2",
      sessionId: "demo",
      questionText: "Which hormone secreted by the parathyroid glands increases blood Calcium (Ca2+) concentrations?",
      optionA: "Calcitonin",
      optionB: "Parathyroid Hormone (PTH)",
      optionC: "Thyroxine (T4)",
      optionD: "Aldosterone",
      correctAnswer: "B",
      explanationEn: "Parathyroid Hormone (PTH) stimulates osteoclasts to dissolve bone matrix, raising blood Ca2+ levels.",
      explanationUr: "Parathyroid Hormone (PTH) bones se Calcium release karwa kar blood Ca2+ level barhata hai.",
      difficulty: "Medium",
      topic: "Endocrine System of Man",
    },
    {
      id: "ch6-q3",
      sessionId: "demo",
      questionText: "Hypersecretion of Growth Hormone (GH) in adults after epiphyseal plate closure leads to:",
      optionA: "Gigantism",
      optionB: "Acromegaly",
      optionC: "Cushing's Syndrome",
      optionD: "Dwarfism",
      correctAnswer: "B",
      explanationEn: "Acromegaly causes thickening of facial bones, hands, and feet due to adult GH hypersecretion.",
      explanationUr: "Adults mein Growth Hormone ziada nikalne se hathon, paon aur chehre ki hadiyan moti ho jati hain jise Acromegaly kehte hain.",
      difficulty: "Hard",
      topic: "Endocrine System of Man",
    },
    {
      id: "ch6-q4",
      sessionId: "demo",
      questionText: "Which endocrine gland is known as the master gland because its tropic hormones control other endocrine glands?",
      optionA: "Thyroid gland",
      optionB: "Pituitary gland (Hypophysis)",
      optionC: "Adrenal gland",
      optionD: "Pancreas",
      correctAnswer: "B",
      explanationEn: "The pituitary gland releases tropic hormones (TSH, ACTH, FSH, LH) regulating thyroid, adrenal cortex, and gonads.",
      explanationUr: "Pituitary gland doosre tamoom glands ko control karne wale hormones nikalta hai is liye ise Master Gland kehte hain.",
      difficulty: "Easy",
      topic: "Endocrine System of Man",
    },
  ],

  // Chapter 7: Skeletal System of Man
  7: [
    {
      id: "ch7-q1",
      sessionId: "demo",
      questionText: "According to the sliding filament model of muscle contraction, Calcium ions (Ca2+) bind to:",
      optionA: "Myosin head",
      optionB: "Troponin",
      optionC: "Tropomyosin",
      optionD: "Actin filament",
      correctAnswer: "B",
      explanationEn: "Calcium ions released from sarcoplasmic reticulum bind to troponin, causing tropomyosin to shift away from actin active sites.",
      explanationUr: "Calcium ions troponin se bind karte hain jis se tropomyosin shift hoti hai aur myosin binding site khulti hai.",
      difficulty: "Medium",
      topic: "Skeletal System of Man",
    },
    {
      id: "ch7-q2",
      sessionId: "demo",
      questionText: "What is the functional contractile unit of a myofibril bounded by two adjacent Z-discs?",
      optionA: "Sarcolemma",
      optionB: "Sarcomere",
      optionC: "Sarcoplasm",
      optionD: "H-zone",
      correctAnswer: "B",
      explanationEn: "A sarcomere is the microscopic functional repeating unit of striated muscle extending from one Z-disc to the next Z-disc.",
      explanationUr: "Do Z-discs ke darmiyan muscle fiber ki contraction ki functional unit ko Sarcomere kehte hain.",
      difficulty: "Easy",
      topic: "Skeletal System of Man",
    },
    {
      id: "ch7-q3",
      sessionId: "demo",
      questionText: "Why does Rigor Mortis occur in skeletal muscles shortly after death?",
      optionA: "Excessive Ca2+ pumping out of sarcoplasm",
      optionB: "Lack of ATP prevents detachment of myosin heads from actin filaments",
      optionC: "Lactic acid buildup destroys Z-discs",
      optionD: "Troponin degradation",
      correctAnswer: "B",
      explanationEn: "ATP is required to break actin-myosin cross-bridges; post-mortem ATP depletion locks myosin heads onto actin.",
      explanationUr: "Maut ke baad ATP na hone ki waja se myosin heads actin se alag nahi ho pate jis se muscles akad jate hain (Rigor Mortis).",
      difficulty: "Hard",
      topic: "Skeletal System of Man",
    },
    {
      id: "ch7-q4",
      sessionId: "demo",
      questionText: "Which connective tissue structure attaches skeletal muscle directly to bone?",
      optionA: "Ligament",
      optionB: "Tendon",
      optionC: "Cartilage",
      optionD: "Fascia",
      correctAnswer: "B",
      explanationEn: "Tendons are dense collagenous connective tissues that attach muscle to bone, whereas ligaments connect bone to bone.",
      explanationUr: "Tendon muscle ko bone se jodta hai, jabke ligament bone ko bone se jodta hai.",
      difficulty: "Easy",
      topic: "Skeletal System of Man",
    },
  ],

  // Chapter 8: Thermoregulation & Homeostasis
  8: [
    {
      id: "ch8-q1",
      sessionId: "demo",
      questionText: "Which central nervous system structure acts as the body's primary thermoregulatory thermostat?",
      optionA: "Cerebrum",
      optionB: "Hypothalamus",
      optionC: "Cerebellum",
      optionD: "Medulla oblongata",
      correctAnswer: "B",
      explanationEn: "The preoptic area of the hypothalamus senses core body temperature and initiates cooling or warming physiological responses.",
      explanationUr: "Hypothalamus body temperature monitor karke internal thermostat ka kaam karta hai.",
      difficulty: "Easy",
      topic: "Thermoregulation & Homeostasis",
    },
    {
      id: "ch8-q2",
      sessionId: "demo",
      questionText: "What physiological response occurs in human skin when exposed to high ambient environmental temperatures?",
      optionA: "Vasoconstriction of cutaneous arterioles",
      optionB: "Vasodilation of cutaneous arterioles and activation of sweat glands",
      optionC: "Shivering thermogenesis",
      optionD: "Piloerection (goosebumps)",
      correctAnswer: "B",
      explanationEn: "Cutaneous vasodilation increases blood flow to the skin surface so heat can radiate out, while sweat evaporation cools the body.",
      explanationUr: "Gharmi mein skin ki blood vessels dilate (khul) jati hain aur sweat glands se pasina nikalta hai taake jism thanda ho.",
      difficulty: "Medium",
      topic: "Thermoregulation & Homeostasis",
    },
    {
      id: "ch8-q3",
      sessionId: "demo",
      questionText: "Which type of feedback mechanism counteracts a change in a physiological variable to restore set-point homeostasis?",
      optionA: "Positive feedback",
      optionB: "Negative feedback",
      optionC: "Feedforward regulation",
      optionD: "Cascade amplifications",
      correctAnswer: "B",
      explanationEn: "Negative feedback loops reverse initial deviations from normal set-points to maintain internal stability.",
      explanationUr: "Negative feedback mechanism jism ke andar badlao ko wapas normal level par la kar homeostasis maintain karta hai.",
      difficulty: "Easy",
      topic: "Thermoregulation & Homeostasis",
    },
    {
      id: "ch8-q4",
      sessionId: "demo",
      questionText: "Animals that generate their own internal body heat through high metabolic rates are classified as:",
      optionA: "Ectotherms",
      optionB: "Endotherms",
      optionC: "Poikilotherms",
      optionD: "Heterotherms",
      correctAnswer: "B",
      explanationEn: "Endotherms (birds and mammals) produce internal metabolic heat to maintain a constant body temperature.",
      explanationUr: "Endotherms (jaise insan aur parinde) apne jism ke andar metabolic heat paida karke temperature maintain karte hain.",
      difficulty: "Easy",
      topic: "Thermoregulation & Homeostasis",
    },
  ],

  // Chapter 9: Immunity
  9: [
    {
      id: "ch9-q1",
      sessionId: "demo",
      questionText: "Humoral adaptive immunity is mediated primarily by antigen-specific antibodies secreted by:",
      optionA: "Cytotoxic T cells (CD8+)",
      optionB: "Plasma B cells",
      optionC: "Natural Killer (NK) cells",
      optionD: "Macrophages",
      correctAnswer: "B",
      explanationEn: "Activated B lymphocytes differentiate into plasma cells, which secrete high quantities of circulating immunoglobulins (antibodies).",
      explanationUr: "Plasma B cells blood aur lymph mein specific antibodies secrete karke Humoral Immunity provide karti hain.",
      difficulty: "Easy",
      topic: "Immunity",
    },
    {
      id: "ch9-q2",
      sessionId: "demo",
      questionText: "Which immunoglobulin antibody class is the most abundant in human blood and capable of crossing the placenta?",
      optionA: "IgA",
      optionB: "IgE",
      optionC: "IgG",
      optionD: "IgM",
      correctAnswer: "C",
      explanationEn: "IgG constitutes ~75-80% of human antibodies and is actively transported across the placenta to confer passive immunity to the fetus.",
      explanationUr: "IgG antibody blood mein sab se ziada hoti hai aur placenta cross karke unborn baby ko immunity deti hai.",
      difficulty: "Medium",
      topic: "Immunity",
    },
    {
      id: "ch9-q3",
      sessionId: "demo",
      questionText: "Which immune cell type directly destroys virus-infected or cancerous host cells by releasing perforins and granzymes?",
      optionA: "Helper T cells (CD4+)",
      optionB: "Cytotoxic T cells (CD8+)",
      optionC: "B memory cells",
      optionD: "Mast cells",
      correctAnswer: "B",
      explanationEn: "Cytotoxic T lymphocytes recognize foreign antigens on MHC-I and release perforin (pore-forming) and granzyme (apoptosis-inducing) proteins.",
      explanationUr: "Cytotoxic T cells perforins aur granzymes nikal kar infected cells ko direct destroy karti hain.",
      difficulty: "Medium",
      topic: "Immunity",
    },
    {
      id: "ch9-q4",
      sessionId: "demo",
      questionText: "Monoclonal antibodies are manufactured industrially by fusing B cells with myeloma cancer cells using:",
      optionA: "PCR technology",
      optionB: "Hybridoma technology",
      optionC: "CRISPR-Cas9",
      optionD: "Restriction digestion",
      correctAnswer: "B",
      explanationEn: "Hybridoma technology fuses antibody-producing B cells with immortal myeloma cells to produce monoclonal antibodies continuously.",
      explanationUr: "Hybridoma technology B cells ko cancer cells ke sath fuse karke mass level par Monoclonal Antibodies banati hai.",
      difficulty: "Hard",
      topic: "Immunity",
    },
  ],

  // Chapter 10: Biotechnology
  10: [
    {
      id: "ch10-q1",
      sessionId: "demo",
      questionText: "Which enzymes act as 'molecular scissors' by cleaving DNA at specific palindromic recognition sequences?",
      optionA: "DNA Ligases",
      optionB: "Restriction Endonucleases",
      optionC: "DNA Polymerases",
      optionD: "Reverse Transcriptases",
      correctAnswer: "B",
      explanationEn: "Restriction endonucleases recognize specific palindromic DNA sequences and cut phosphodiester bonds to form sticky or blunt ends.",
      explanationUr: "Restriction endonuclease enzymes DNA ko specific palindromic sites par molecular scissors ki tarah cut karte hain.",
      difficulty: "Easy",
      topic: "Biotechnology",
    },
    {
      id: "ch10-q2",
      sessionId: "demo",
      questionText: "In Polymerase Chain Reaction (PCR), what heat-stable enzyme is used for automated DNA strand extension at 72°C?",
      optionA: "Human DNA Polymerase III",
      optionB: "Taq Polymerase (from Thermus aquaticus)",
      optionC: "RNA Polymerase II",
      optionD: "Helicase",
      correctAnswer: "B",
      explanationEn: "Taq Polymerase isolated from thermophilic bacteria withstands high PCR denaturation temperatures (94°C) and synthesizes DNA at 72°C.",
      explanationUr: "Taq Polymerase high temperature par zinda rehne wala enzyme hai jo PCR mein 72°C par DNA copy karta hai.",
      difficulty: "Medium",
      topic: "Biotechnology",
    },
    {
      id: "ch10-q3",
      sessionId: "demo",
      questionText: "What enzyme synthesizes complementary DNA (cDNA) using a mature eukaryotic mRNA template?",
      optionA: "DNA Ligase",
      optionB: "Reverse Transcriptase",
      optionC: "Restriction Enzyme",
      optionD: "Taq Polymerase",
      correctAnswer: "B",
      explanationEn: "Reverse transcriptase converts eukaryotic mRNA into intron-free cDNA for cloning into bacterial expression vectors.",
      explanationUr: "Reverse Transcriptase enzyme mRNA template se intron-free complementary DNA (cDNA) banata hai.",
      difficulty: "Medium",
      topic: "Biotechnology",
    },
    {
      id: "ch10-q4",
      sessionId: "demo",
      questionText: "In Agarose Gel Electrophoresis, DNA fragments migrate toward which electrode based on their size?",
      optionA: "Negative cathode (smaller move slower)",
      optionB: "Positive anode (smaller move faster)",
      optionC: "Neutral center",
      optionD: "Cathode (larger move faster)",
      correctAnswer: "B",
      explanationEn: "Negatively charged phosphate backbones cause DNA to migrate toward the positive anode; smaller fragments move faster through gel pores.",
      explanationUr: "Negatively charged DNA positive anode ki taraf jata hai aur chote fragments tezi se aage nikalte hain.",
      difficulty: "Medium",
      topic: "Biotechnology",
    },
  ],

  // Chapter 11: Biostatistics & Data Handling
  11: [
    {
      id: "ch11-q1",
      sessionId: "demo",
      questionText: "The middle observation value separating the higher half from the lower half of an ordered data series is the:",
      optionA: "Mean",
      optionB: "Median",
      optionC: "Mode",
      optionD: "Variance",
      correctAnswer: "B",
      explanationEn: "The median is the exact middle numerical value when data points are arranged in ascending or descending order.",
      explanationUr: "Median tarteeb shuda numbers ke dataset ki bilkul darmiyani (middle) value hoti hai.",
      difficulty: "Easy",
      topic: "Biostatistics & Data Handling",
    },
    {
      id: "ch11-q2",
      sessionId: "demo",
      questionText: "In a statistical Gaussian Normal Distribution curve, approximately what percentage of observations fall within ±1 Standard Deviation of the mean?",
      optionA: "50%",
      optionB: "68%",
      optionC: "95%",
      optionD: "99.7%",
      correctAnswer: "B",
      explanationEn: "According to the empirical rule, ~68% of data falls within 1 SD, ~95% within 2 SD, and 99.7% within 3 SD in normal distribution.",
      explanationUr: "Normal distribution curve mein taqreeban 68% values ±1 Standard Deviation ke andar ati hain.",
      difficulty: "Medium",
      topic: "Biostatistics & Data Handling",
    },
    {
      id: "ch11-q3",
      sessionId: "demo",
      questionText: "A Null Hypothesis (H0) in medical research assumes that:",
      optionA: "The experimental treatment is highly effective",
      optionB: "There is no significant difference or effect between the study groups",
      optionC: "The sample size is too small",
      optionD: "The p-value is greater than 1",
      correctAnswer: "B",
      explanationEn: "The Null Hypothesis (H0) posits that observed differences between groups are due solely to random chance.",
      explanationUr: "Null Hypothesis (H0) ye assume karti hai ke groups ke darmiyan koi genuine farq nahi hai.",
      difficulty: "Easy",
      topic: "Biostatistics & Data Handling",
    },
    {
      id: "ch11-q4",
      sessionId: "demo",
      questionText: "In hypothesis testing, a p-value threshold less than 0.05 (p < 0.05) indicates that the result is:",
      optionA: "Statistically insignificant (accept H0)",
      optionB: "Statistically significant (reject H0)",
      optionC: "Inconclusive",
      optionD: "Biased sample",
      correctAnswer: "B",
      explanationEn: "A p-value < 0.05 means there is less than a 5% probability that the result occurred by chance, rejecting the null hypothesis.",
      explanationUr: "p-value < 0.05 ka matlab hai ke result statistically significant hai aur Null Hypothesis (H0) reject hoti hai.",
      difficulty: "Medium",
      topic: "Biostatistics & Data Handling",
    },
  ],

  // Chapter 12: Structural & Computational Biology
  12: [
    {
      id: "ch12-q1",
      sessionId: "demo",
      questionText: "Alpha-helices and Beta-pleated sheets are examples of which protein structural organization level?",
      optionA: "Primary structure",
      optionB: "Secondary structure",
      optionC: "Tertiary structure",
      optionD: "Quaternary structure",
      correctAnswer: "B",
      explanationEn: "Secondary structures are local folding patterns formed by hydrogen bonds between backbone N-H and C=O groups.",
      explanationUr: "Alpha-helices aur Beta-sheets backbone hydrogen bonds se banne wali secondary protein structure hain.",
      difficulty: "Easy",
      topic: "Structural & Computational Biology",
    },
    {
      id: "ch12-q2",
      sessionId: "demo",
      questionText: "Which public biological database is the worldwide repository for 3D atomic coordinates of proteins and nucleic acids?",
      optionA: "GenBank",
      optionB: "Protein Data Bank (PDB)",
      optionC: "PubMed",
      optionD: "BLAST",
      correctAnswer: "B",
      explanationEn: "The Protein Data Bank (PDB) archives experimentally determined 3D structures from X-ray crystallography, NMR, and Cryo-EM.",
      explanationUr: "Protein Data Bank (PDB) dunia bhar ke 3D protein structures ki central repository database hai.",
      difficulty: "Easy",
      topic: "Structural & Computational Biology",
    },
    {
      id: "ch12-q3",
      sessionId: "demo",
      questionText: "What sequence alignment tool is widely used in bioinformatics to find homologous regions between nucleotide or protein sequences?",
      optionA: "PCR",
      optionB: "BLAST (Basic Local Alignment Search Tool)",
      optionC: "AlphaFold",
      optionD: "PyMOL",
      correctAnswer: "B",
      explanationEn: "BLAST compares query sequences against databases to calculate statistical significance of sequence similarity matches.",
      explanationUr: "BLAST tool bioinformatics mein unknown sequences ki similarity aur homology match karne ke liye use hota hai.",
      difficulty: "Medium",
      topic: "Structural & Computational Biology",
    },
    {
      id: "ch12-q4",
      sessionId: "demo",
      questionText: "What main thermodynamic force drives non-polar hydrophobic amino acid side chains into the internal core of a folded protein?",
      optionA: "Ionic bonding",
      optionB: "Hydrophobic effect",
      optionC: "Disulfide bridges",
      optionD: "Peptide hydrolysis",
      correctAnswer: "B",
      explanationEn: "Burying non-polar side chains inside the protein core minimizes hydrophobic contact with water, increasing entropy of surrounding water.",
      explanationUr: "Hydrophobic effect ke zariye non-polar amino acids protein ke andar chup jate hain taake water se bacha ja sake.",
      difficulty: "Hard",
      topic: "Structural & Computational Biology",
    },
  ],

  // Chapter 13: Climate Change
  13: [
    {
      id: "ch13-q1",
      sessionId: "demo",
      questionText: "Which anthropogenic gas is the primary contributor to global enhanced greenhouse warming?",
      optionA: "Methane (CH4)",
      optionB: "Carbon Dioxide (CO2)",
      optionC: "Nitrous Oxide (N2O)",
      optionD: "Chlorofluorocarbons (CFCs)",
      correctAnswer: "B",
      explanationEn: "Carbon Dioxide (CO2) released from fossil fuel burning accounts for ~65-75% of human-induced radiative heat forcing.",
      explanationUr: "Fossil fuels ke jalne se nikalne wali Carbon Dioxide (CO2) global warming ki sab se bari greenhouse gas hai.",
      difficulty: "Easy",
      topic: "Climate Change",
    },
    {
      id: "ch13-q2",
      sessionId: "demo",
      questionText: "How does excess atmospheric Carbon Dioxide (CO2) absorption cause Ocean Acidification?",
      optionA: "CO2 dissolves in water to form Carbonic Acid (H2CO3), releasing H+ ions and lowering ocean pH",
      optionB: "CO2 reacts with NaCl to form Hydrochloric acid",
      optionC: "CO2 consumes ocean oxygen",
      optionD: "CO2 increases ocean salinity",
      correctAnswer: "A",
      explanationEn: "CO2 + H2O <-> H2CO3 <-> H+ + HCO3-. Increased H+ ions decrease ocean pH and reduce carbonate ions needed by coral reefs.",
      explanationUr: "CO2 paani mein mil kar Carbonic Acid banati hai jis se H+ ions barhte hain aur ocean ka pH gir jata hai.",
      difficulty: "Medium",
      topic: "Climate Change",
    },
    {
      id: "ch13-q3",
      sessionId: "demo",
      questionText: "What chemical pollutants released into the atmosphere were primarily responsible for stratospheric Ozone layer depletion?",
      optionA: "Sulfur dioxide",
      optionB: "Chlorofluorocarbons (CFCs)",
      optionC: "Carbon monoxide",
      optionD: "Methane",
      correctAnswer: "B",
      explanationEn: "UV radiation breaks CFCs to release free chlorine radicals, which catalyze the breakdown of protective stratospheric ozone (O3).",
      explanationUr: "Chlorofluorocarbons (CFCs) se nikalne wale chlorine radicals ozone layer (O3) ko destroy karte hain.",
      difficulty: "Easy",
      topic: "Climate Change",
    },
    {
      id: "ch13-q4",
      sessionId: "demo",
      questionText: "Agricultural fertilizer runoff containing excessive nitrogen and phosphorus causes aquatic oxygen depletion through:",
      optionA: "Ocean acidification",
      optionB: "Eutrophication (algal blooms and hypoxia)",
      optionC: "Thermal pollution",
      optionD: "Ozone depletion",
      correctAnswer: "B",
      explanationEn: "Nutrient runoff fuels rapid algal growth; when algae die, bacterial decomposition consumes dissolved oxygen, creating hypoxia (dead zones).",
      explanationUr: "Fertilizer runoff se algae ki overflow growth hoti hai; unki decomposition se paani ki oxygen khatam (Eutrophication) ho jati hai.",
      difficulty: "Medium",
      topic: "Climate Change",
    },
  ],

  // Chapter 14: Selected Topics
  14: [
    {
      id: "ch14-q1",
      sessionId: "demo",
      questionText: "What is the net movement of water molecules across a selectively permeable membrane from high to low water potential called?",
      optionA: "Active transport",
      optionB: "Osmosis",
      optionC: "Endocytosis",
      optionD: "Facilitated diffusion",
      correctAnswer: "B",
      explanationEn: "Osmosis is the passive diffusion of solvent (water) across a semipermeable membrane down a water potential gradient.",
      explanationUr: "Paani ka semipermeable membrane ke zariye high concentration se low concentration ki taraf jana Osmosis kehlata hai.",
      difficulty: "Easy",
      topic: "Selected Topics",
    },
    {
      id: "ch14-q2",
      sessionId: "demo",
      questionText: "During which interphase stage of the cell cycle does semi-conservative nuclear DNA replication take place?",
      optionA: "G1 phase",
      optionB: "S phase (Synthesis)",
      optionC: "G2 phase",
      optionD: "M phase (Mitosis)",
      correctAnswer: "B",
      explanationEn: "The S (Synthesis) phase of interphase is dedicated to duplicating cellular DNA so daughter cells receive identical genomes.",
      explanationUr: "Cell cycle ke S (Synthesis) phase mein nuclear DNA ki mukammal replication hoti hai.",
      difficulty: "Easy",
      topic: "Selected Topics",
    },
    {
      id: "ch14-q3",
      sessionId: "demo",
      questionText: "Programmed physiological cell death mediated by caspase enzyme activation without cell lysis is known as:",
      optionA: "Necrosis",
      optionB: "Apoptosis",
      optionC: "Lysis",
      optionD: "Phagocytosis",
      correctAnswer: "B",
      explanationEn: "Apoptosis is orderly programmed cell suicide characterized by membrane blebbing, DNA fragmentation, and caspase activation.",
      explanationUr: "Apoptosis cell ki apni qanooni programmed maut hoti hai jis mein caspases enzymes involve hote hain.",
      difficulty: "Medium",
      topic: "Selected Topics",
    },
    {
      id: "ch14-q4",
      sessionId: "demo",
      questionText: "Which intracellular molecule acts as a classic second messenger downstream of G-protein coupled receptor activation?",
      optionA: "ATP",
      optionB: "Cyclic AMP (cAMP)",
      optionC: "Glucose",
      optionD: "Pyruvate",
      correctAnswer: "B",
      explanationEn: "Adenylate cyclase converts ATP into cyclic AMP (cAMP), which activates Protein Kinase A to relay intracellular signal cascades.",
      explanationUr: "Cyclic AMP (cAMP) cell ke andar second messenger ka kaam karke hormone signals aage bhejta hai.",
      difficulty: "Medium",
      topic: "Selected Topics",
    },
  ],

  // Chapter 15: Pharmacological Drugs
  15: [
    {
      id: "ch15-q1",
      sessionId: "demo",
      questionText: "In drug clinical trials, Phase I testing is conducted primarily on which participant group to evaluate safety and metabolism?",
      optionA: "1,000 to 3,000 diseased patients",
      optionB: "20 to 100 healthy human volunteers",
      optionC: "Post-market general public populations",
      optionD: "Animals in pre-clinical screening",
      correctAnswer: "B",
      explanationEn: "Phase I clinical trials evaluate safety, tolerability, dosage range, and pharmacokinetics in a small group of 20-100 healthy human volunteers.",
      explanationUr: "Phase I clinical trials mein 20 se 100 sehat-mand human volunteers par drug ki safety aur dosage test ki jati hai.",
      difficulty: "Medium",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q2",
      sessionId: "demo",
      questionText: "Which clinical trial phase is known as Post-Marketing Surveillance to monitor long-term safety and rare side effects after regulatory approval?",
      optionA: "Phase I",
      optionB: "Phase II",
      optionC: "Phase III",
      optionD: "Phase IV",
      correctAnswer: "D",
      explanationEn: "Phase IV trials occur after drug approval to track long-term safety, rare adverse reactions, and real-world interactions in large populations.",
      explanationUr: "Phase IV trials drug approval ke baad ki jati hain taake public population mein long-term safety aur rare side effects track ho sakein.",
      difficulty: "Easy",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q3",
      sessionId: "demo",
      questionText: "Phase II Clinical Trials focus primarily on evaluating drug efficacy and short-term risks in which participant group?",
      optionA: "20-100 healthy volunteers",
      optionB: "100 to 500 patients suffering from the target disease",
      optionC: "1,000-3,000 patients across multiple countries",
      optionD: "Animal models",
      correctAnswer: "B",
      explanationEn: "Phase II trials administer the drug to 100-500 patients with the target disease to assess therapeutic effectiveness and short-term side effects.",
      explanationUr: "Phase II trials mein 100 se 500 bimari wale patients par dawa ki bimari khatam karne ki salahiyat (efficacy) test hoti hai.",
      difficulty: "Medium",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q4",
      sessionId: "demo",
      questionText: "What is the primary objective of Phase III Large-Scale Clinical Trials?",
      optionA: "Pre-clinical animal toxicity screening",
      optionB: "Confirming efficacy and safety in 1,000-3,000 patients against standard treatments",
      optionC: "Determining chemical synthesis pathways",
      optionD: "Over-the-counter pricing regulation",
      correctAnswer: "B",
      explanationEn: "Phase III trials evaluate 1,000-3,000 patients across clinical centers to confirm therapeutic benefits, monitor side effects, and compare with current standard care.",
      explanationUr: "Phase III trials 1,000 se 3,000 patients par dawai ki efficacy aur safety ko standard treatments se mukabla karti hain.",
      difficulty: "Hard",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q5",
      sessionId: "demo",
      questionText: "The study of how the human body processes a drug through Absorption, Distribution, Metabolism, and Excretion is termed:",
      optionA: "Pharmacodynamics",
      optionB: "Pharmacokinetics (ADME)",
      optionC: "Toxicology",
      optionD: "Pharmacogenomics",
      correctAnswer: "B",
      explanationEn: "Pharmacokinetics describes what the human body does to a drug over time through ADME processes.",
      explanationUr: "Pharmacokinetics (ADME) ye bayan karti hai ke insani jism dawai ke sath kya karta hai (Absorption, Distribution, Metabolism, Excretion).",
      difficulty: "Easy",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q6",
      sessionId: "demo",
      questionText: "A drug that binds to a specific cellular receptor and triggers a full biological response is classified as a(n):",
      optionA: "Antagonist",
      optionB: "Agonist",
      optionC: "Inverse Agonist",
      optionD: "Competitive Inhibitor",
      correctAnswer: "B",
      explanationEn: "An agonist mimics endogenous ligands by binding and activating cell surface or intracellular receptors.",
      explanationUr: "Agonist wo dawa hoti hai jo receptor se bind hokar full biological response activate karti hai.",
      difficulty: "Easy",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q7",
      sessionId: "demo",
      questionText: "What parameter measures a drug's safety margin by calculating the ratio of Toxic Dose (TD50) to Effective Dose (ED50)?",
      optionA: "Half-life (t1/2)",
      optionB: "Therapeutic Index (TI)",
      optionC: "Bioavailability",
      optionD: "Clearance rate",
      correctAnswer: "B",
      explanationEn: "Therapeutic Index (TI = TD50 / ED50) quantifies safety; drugs with a high TI have a wide safety margin.",
      explanationUr: "Therapeutic Index (TI) dawai ki safety margin batata hai; ziada TI ka matlab ziada mahfooz dawai.",
      difficulty: "Medium",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q8",
      sessionId: "demo",
      questionText: "The time required for blood plasma concentration of a drug to decrease to 50% of its peak level is defined as its:",
      optionA: "Bioavailability",
      optionB: "Elimination Half-life (t1/2)",
      optionC: "Steady state concentration",
      optionD: "Volume of distribution",
      correctAnswer: "B",
      explanationEn: "Elimination half-life (t1/2) determines dosage frequency needed to maintain therapeutic blood levels.",
      explanationUr: "Plasma mein dawai ki miqdar adhi (50%) reh jaane ke waqt ko Elimination Half-life (t1/2) kehte hain.",
      difficulty: "Easy",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q9",
      sessionId: "demo",
      questionText: "Which hepatic enzyme system is primarily responsible for Phase I drug oxidation and metabolism in humans?",
      optionA: "Renal Tubular Enzymes",
      optionB: "Cytochrome P450 (CYP450) monooxygenases",
      optionC: "Pancreatic Lipase",
      optionD: "Gastric Pepsin",
      correctAnswer: "B",
      explanationEn: "Hepatic Cytochrome P450 enzymes metabolize lipophilic drugs into polar compounds for urinary excretion.",
      explanationUr: "Jigar (liver) mein Cytochrome P450 enzymes dawaiyon ko breakdown aur metabolize karte hain.",
      difficulty: "Hard",
      topic: "Pharmacological Drugs",
    },
    {
      id: "ch15-q10",
      sessionId: "demo",
      questionText: "Bacterial resistance to beta-lactam antibiotics (like Penicillin) commonly occurs via bacterial production of:",
      optionA: "DNA Ligase",
      optionB: "Beta-lactamase (Penicillinase) enzymes",
      optionC: "Reverse Transcriptase",
      optionD: "Restriction Enzymes",
      correctAnswer: "B",
      explanationEn: "Beta-lactamase enzymes cleave the beta-lactam ring of penicillins and cephalosporins, inactivating the antibiotic.",
      explanationUr: "Bacteria beta-lactamase enzymes kharij karke Penicillin jaisi antibiotics ko inactivate kar dete hain.",
      difficulty: "Medium",
      topic: "Pharmacological Drugs",
    },
  ],
};

/**
 * Get distinct, non-repeating questions for any chapter strictly grounded in that chapter's topic.
 */
export function getQuestionsForChapter(
  chapter: string | number,
  topicName: string,
  requestedCount = 10,
  excludeTexts: string[] = []
): Question[] {
  const chapterNumClean = parseChapterNumber(chapter);
  const baseQuestions = ALL_CHAPTER_QUESTIONS[chapterNumClean] || ALL_CHAPTER_QUESTIONS[1];

  const excludedSet = new Set(excludeTexts.map((t) => t.trim().toLowerCase()));

  // Filter out any previously asked questions for this topic
  const availableQuestions = baseQuestions.filter(
    (q) => !excludedSet.has(q.questionText.trim().toLowerCase())
  );

  // If all static questions were previously asked, reset pool from base
  const pool = availableQuestions.length > 0 ? availableQuestions : baseQuestions;

  // Shuffle pool for randomized presentation
  const shuffled = [...pool].sort(() => Math.random() - 0.5);

  const result: Question[] = [];
  const totalPool = shuffled.length;

  for (let i = 0; i < requestedCount; i++) {
    const base = shuffled[i % totalPool];
    const isRepeatCycle = Math.floor(i / totalPool);

    result.push({
      ...base,
      id: `ch${chapterNumClean}-q-${Date.now()}-${i + 1}-${Math.random().toString(36).substring(2, 6)}`,
      questionText:
        isRepeatCycle === 0
          ? base.questionText
          : `[Concept Focus ${i + 1}] ${base.questionText}`,
      topic: topicName || base.topic,
    });
  }

  return result;
}
